name: Setup and run supersim
on:  [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Confirm forge is installed
        run: forge --version
      - name: Install supersim
        run: brew install ethereum-optimism/tap/supersim
      - name: Confirm supersim is installed
        run: supersim --version
      - name: Fork
        run: supersim fork  --l2.host=0.0.0.0 --l2.starting.port=4444 --chains=op,base > /dev/null 2>&1 &
      - name: Test fork
        run: cast call 0x7F6D3A4c8a1111DDbFe282794f4D608aB7Cb23A2 "MAX_TOKENS()(uint256)" --rpc-url http://localhost:4444
