name: Setup and run supersim
on:  [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Confirm forge is installed
        run: forge --version
