name: Setup and run supersim
on:  [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Confirm forge is installed
        run: forge --version
      - name: Install supersim
        run: brew install ethereum-optimism/tap/supersim
      - name: Confirm supersim is installed
        run: supersim --version
