name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: velodrome-finance/sugar-sdk/.github/workflows/supersim.yaml@main
      - uses: fastai/workflows/nbdev-ci@master
